inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'features/**/*'

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

