# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/matriculas', type: :request do
  let(:user) do
    User.create!(name: 'Test User', email: 'test@example.com', password: 'password', matricula: '12345', role: 'admin')
  end
  # This should return the minimal set of attributes required to create a valid
  # Matricula. As you add validations to Matricula, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      user_id: user.id,
      turma_id: turma.id
    }
  end
  let(:invalid_attributes) do
    {
      user_id: nil,
      turma_id: nil
    }
  end
  let(:curso) { Curso.create!(nome: 'Test Course') }
  let(:disciplina) { Disciplina.create!(nome: 'Test Discipline', curso: curso) }
  let(:professor) do
    User.create!(name: 'Professor', email: 'professor@example.com', password: 'password', matricula: '67890',
                 role: 'professor')
  end
  let(:turma) { Turma.create!(disciplina: disciplina, professor: professor, semestre: '2024.1') }

  before do
    login_as(user, scope: :user)
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Matricula.create! valid_attributes
      get matriculas_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      matricula = Matricula.create! valid_attributes
      get matricula_url(matricula)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_matricula_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      matricula = Matricula.create! valid_attributes
      get edit_matricula_url(matricula)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Matricula' do
        expect do
          post matriculas_url, params: { matricula: valid_attributes }
        end.to change(Matricula, :count).by(1)
      end

      it 'redirects to the created matricula' do
        post matriculas_url, params: { matricula: valid_attributes }
        expect(response).to redirect_to(matricula_url(Matricula.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Matricula' do
        expect do
          post matriculas_url, params: { matricula: invalid_attributes }
        end.not_to change(Matricula, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post matriculas_url, params: { matricula: invalid_attributes }
        expect(response).to have_http_status(422)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          user_id: user.id
        }
      end

      it 'updates the requested matricula' do
        matricula = Matricula.create! valid_attributes
        patch matricula_url(matricula), params: { matricula: new_attributes }
        matricula.reload
        expect(matricula.user_id).to eq(new_attributes[:user_id])
      end

      it 'redirects to the matricula' do
        matricula = Matricula.create! valid_attributes
        patch matricula_url(matricula), params: { matricula: new_attributes }
        matricula.reload
        expect(response).to redirect_to(matricula_url(matricula))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        matricula = Matricula.create! valid_attributes
        patch matricula_url(matricula), params: { matricula: invalid_attributes }
        expect(response).to have_http_status(422)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested matricula' do
      matricula = Matricula.create! valid_attributes
      expect do
        delete matricula_url(matricula)
      end.to change(Matricula, :count).by(-1)
    end

    it 'redirects to the matriculas list' do
      matricula = Matricula.create! valid_attributes
      delete matricula_url(matricula)
      expect(response).to redirect_to(matriculas_url)
    end
  end
end
