require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/matriculas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Matricula. As you add validations to Matricula, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Matricula.create! valid_attributes
      get matriculas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      matricula = Matricula.create! valid_attributes
      get matricula_url(matricula)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_matricula_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      matricula = Matricula.create! valid_attributes
      get edit_matricula_url(matricula)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Matricula" do
        expect {
          post matriculas_url, params: { matricula: valid_attributes }
        }.to change(Matricula, :count).by(1)
      end

      it "redirects to the created matricula" do
        post matriculas_url, params: { matricula: valid_attributes }
        expect(response).to redirect_to(matricula_url(Matricula.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Matricula" do
        expect {
          post matriculas_url, params: { matricula: invalid_attributes }
        }.to change(Matricula, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post matriculas_url, params: { matricula: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested matricula" do
        matricula = Matricula.create! valid_attributes
        patch matricula_url(matricula), params: { matricula: new_attributes }
        matricula.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the matricula" do
        matricula = Matricula.create! valid_attributes
        patch matricula_url(matricula), params: { matricula: new_attributes }
        matricula.reload
        expect(response).to redirect_to(matricula_url(matricula))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        matricula = Matricula.create! valid_attributes
        patch matricula_url(matricula), params: { matricula: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested matricula" do
      matricula = Matricula.create! valid_attributes
      expect {
        delete matricula_url(matricula)
      }.to change(Matricula, :count).by(-1)
    end

    it "redirects to the matriculas list" do
      matricula = Matricula.create! valid_attributes
      delete matricula_url(matricula)
      expect(response).to redirect_to(matriculas_url)
    end
  end
end
